CONFIG:
  PECIAX:
    BASE: $SNDATA_ROOT/sample_input_files/DES-SN5YR/base_files/sim/sim_iax_dust.input
    SIMSED_PATH_BINARY: $PLASTICC_MODELS/SIMSED_BINARIES/config_DES_Dovekie
  PECIA91BG:
    BASE: $SNDATA_ROOT/sample_input_files/DES-SN5YR/base_files/sim/sim_ia91bg.input
    SIMSED_PATH_BINARY: $PLASTICC_MODELS/SIMSED_BINARIES/config_DES_Dovekie
  II_TEMPLATES:
    BASE: $SNDATA_ROOT/sample_input_files/DES-SN5YR/base_files/sim/sim_ii_v19_li11revised_nodust.input
    SIMSED_PATH_BINARY: $PLASTICC_MODELS/SIMSED_BINARIES/config_DES_Dovekie
  Ibc_TEMPLATES:
    BASE: $SNDATA_ROOT/sample_input_files/DES-SN5YR/base_files/sim/sim_ibc_v19_li11revised_nodust.input
    SIMSED_PATH_BINARY: $PLASTICC_MODELS/SIMSED_BINARIES/config_DES_Dovekie
  GLOBAL:
    OMEGA_MATTER: 0.315
    OMEGA_LAMBDA: 0.685
    w0_LAMBDA: -1.0
    wa_LAMBDA: 0
    H0: 70.0
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 25
    NGEN_UNIT: 1
    RANSEED_CHANGE: 25 23488
    BATCH_MEM: 8GB
    KCOR_FILE: $SNDATA_ROOT/kcor/Dovekie/calib_DES-SN5YR_DES.fits.gz
    SIMSED_USE_BINARY: 257
  GENVERSION: PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC
OUTPUT:
  name: DATADESSIM_CC
  output_dir: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC
  hash_file: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/hash.txt
  done_file: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/done.txt
  types_dict:
    IA: []
    NONIA:
    - 11
    - 111
    - 91
    - 191
    - 20
    - 120
    - 20
    - 120
  types:
    11: II
    20: II
    91: II
    111: II
    120: II
    191: II
  blind: false
  genversion: PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC
  genprefix: PIP_D5YR_DOV_SIM_NOMINAL_d5036
  ranseed_change: true
  ranseed_change_val: 25 23488
  sim_folders:
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0001
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0002
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0003
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0004
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0005
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0006
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0007
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0008
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0009
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0010
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0011
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0012
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0013
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0014
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0015
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0016
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0017
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0018
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0019
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0020
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0021
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0022
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0023
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0024
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0025
  SURVEY: DES
  SURVEY_ID: 10
  photometry_dirs:
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0001
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0002
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0003
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0004
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0005
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0006
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0007
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0008
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0009
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0010
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0011
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0012
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0013
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0014
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0015
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0016
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0017
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0018
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0019
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0020
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0021
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0022
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0023
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0024
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_CC/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_CC-0025
