CONFIG:
  IA:
    BASE: $SNDATA_ROOT/sample_input_files/DES-SN5YR/base_files/sim/sim_ia_salt_des5yr.input
  GLOBAL:
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 25
    NGEN_UNIT: 1
    RANSEED_CHANGE: 25 23488
    BATCH_MEM: 8GB
    OMEGA_MATTER: 0.315
    OMEGA_LAMBDA: 0.685
    w0_LAMBDA: -1.0
    wa_LAMBDA: 0
    H0: 70.0
    GENMODEL: $SDSS_USERS/BAP37/WHIMBREL/SALT3.DOVEKIE
    KCOR_FILE: $SNDATA_ROOT/kcor/Dovekie/calib_DES-SN5YR_DES.fits.gz
  GENVERSION: PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA
OUTPUT:
  name: DATADESSIM_IA
  output_dir: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA
  hash_file: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/hash.txt
  done_file: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/done.txt
  types_dict:
    IA:
    - 1
    - 101
    NONIA: []
  types:
    1: Ia
    101: Ia
  blind: false
  genversion: PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA
  genprefix: PIP_D5YR_DOV_SIM_NOMINAL_a64ab
  ranseed_change: true
  ranseed_change_val: 25 23488
  sim_folders:
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0001
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0002
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0003
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0004
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0005
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0006
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0007
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0008
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0009
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0010
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0011
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0012
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0013
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0014
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0015
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0016
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0017
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0018
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0019
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0020
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0021
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0022
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0023
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0024
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0025
  SURVEY: DES
  SURVEY_ID: 10
  photometry_dirs:
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0001
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0002
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0003
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0004
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0005
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0006
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0007
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0008
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0009
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0010
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0011
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0012
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0013
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0014
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0015
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0016
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0017
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0018
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0019
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0020
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0021
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0022
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0023
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0024
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_DOV_SIM_NOMINAL/1_SIM/DATADESSIM_IA/PIP_D5YR_DOV_SIM_NOMINAL_DATADESSIM_IA-0025
